server:
  port: 8761
  application:
    name: eurekaService
eureka:
  instance:
    hostname: eurekaService
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    response-cache-update-interval-ms: 5000
    # max-threads-for-peer-replication: 0
